TAG_HELPERS_EXERCISES/TAG_HELPERS_03/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TAG_HELPERS_03.Models
{
    public class Movie
    {
        public int  Id { get; set; }

        public string Title { get; set; }
    }
}

TAG_HELPERS_EXERCISES/TAG_HELPERS_03/ViewModels/ErrorViewModel.cs
using System;

namespace TAG_HELPERS_03.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TAG_HELPERS_EXERCISES/TAG_HELPERS_03/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TAG_HELPERS_03.Models;

namespace TAG_HELPERS_03.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TAG_HELPERS_EXERCISES/TAG_HELPERS_03/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TAG_HELPERS_03.Models;

namespace TAG_HELPERS_03.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult List()
        {
            List<Movie> movies = new List<Movie>()
            {
                new Movie() { Id = 1, Title = "Fight Club" },
                new Movie() { Id = 2, Title = "Forrest Gump" },
                new Movie() { Id = 3, Title = "The Godfather" },
            };
           return View(movies);
        }
    }
}

TAG_HELPERS_EXERCISES/TAG_HELPERS_03/Views/Movie/List.cshtml
@model IEnumerable<TAG_HELPERS_03.Models.Movie>
@{
    Layout = null;
}

    <ul>
        @foreach (var movie in Model)
        {
        <li>
            <a asp-controller="Movie" asp-action="List" asp-route-id="@movie.Id">@movie.Title</a>  <!--a is URL address, form would be just a word-->
        </li>
        }
    </ul>

TAG_HELPERS_EXERCISES/TAG_HELPERS_03/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TAG_HELPERS_03</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TAG_HELPERS_03</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TAG_HELPERS_03 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>